#! /bin/sh

sxhkd &
~/.config/bspwm/startup.sh

bspc monitor -d term web code media 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color '#DC387D'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding -25
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config pointer_modifier move
bspc config pointer_modifier mod1
